
name: paper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  paper:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install
      run: |
        pip install .
    - name: Install paper1 depends
      run: |
        pip install -r paper1_CFs/requirements.txt
    - name: Run paper1 experiments
      run: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --execute "paper1_CFs/*.ipynb" --to notebook --output-dir='temp' --clear-output
    - name: Install paper2 depends
      run: |
        pip install -r paper2_LIME/requirements.txt
    - name: Run paper2 experiments
      run: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --execute "paper2_LIME/*.ipynb" --to notebook --output-dir='temp' --clear-output
